"""SVF verification-sequence generator.

Only IDCODE, BYPASS and SAMPLE/PRELOAD instructions are emitted, so the
sequence never drives the devices' output pins (EXTEST/INTEST are never
loaded). SVF bit streams are built in shift order: bit 0 of a TDI/TDO
value is the first bit shifted.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class SvfDevice:
    name: str
    ir_length: int
    opcodes: dict[str, str] = field(default_factory=dict)  # MSB-left
    capture: str | None = None  # shift-out order, may contain X; None = unknown
    idcode_value: int | None = None
    idcode_mask: int | None = None
    boundary_length: int | None = None
    known: bool = True


def _hex(bits: str) -> str:
    val = 0
    for i, b in enumerate(bits):
        if b == "1":
            val |= 1 << i
    return f"{val:0{max(1, (len(bits) + 3) // 4)}X}"


def _opcode(dev: SvfDevice, kind: str) -> str:
    """Opcode bits (MSB-left) for kind, falling back to BYPASS / all-ones."""
    if kind == "BYPASS":
        return dev.opcodes.get("BYPASS") or "1" * dev.ir_length
    if kind == "IDCODE":
        return dev.opcodes.get("IDCODE") or _opcode(dev, "BYPASS")
    return (dev.opcodes.get("SAMPLE") or dev.opcodes.get("PRELOAD")
            or _opcode(dev, "BYPASS"))


def _ir_stream(chain: list[SvfDevice], kind: str) -> str:
    # TDO-side device receives its opcode first in the stream, LSB first.
    return "".join(_opcode(d, kind)[::-1] for d in reversed(chain))


def _capture_stream(chain: list[SvfDevice]) -> tuple[str, str]:
    bits, mask = "", ""
    for d in reversed(chain):
        if d.capture:
            bits += "".join(c if c in "01" else "0" for c in d.capture)
            mask += "".join("1" if c in "01" else "0" for c in d.capture)
        else:
            bits += "0" * d.ir_length
            mask += "0" * d.ir_length
    return bits, mask


def generate_svf(chain: list[SvfDevice]) -> str:
    """chain: TDI-side first. Returns the SVF text."""
    out: list[str] = []
    emit = out.append
    total_ir = sum(d.ir_length for d in chain)
    cap_bits, cap_mask = _capture_stream(chain)

    emit("! JTAG scan-chain verification sequence (generated by jtag-recon)")
    emit("! Uses only IDCODE, BYPASS and SAMPLE/PRELOAD:")
    emit("! device output pins are never driven (no EXTEST/INTEST/CLAMP).")
    emit("TRST OFF;")
    emit("ENDIR IDLE;")
    emit("ENDDR IDLE;")
    emit("STATE RESET;")
    emit("STATE IDLE;")

    emit("")
    emit("! --- step 1: load BYPASS into every device, count the chain ---")
    emit(f"SIR {total_ir} TDI ({_hex(_ir_stream(chain, 'BYPASS'))}) "
         f"TDO ({_hex(cap_bits)}) MASK ({_hex(cap_mask)});")
    bypass_tdo = "".join("0" for _ in chain)
    bypass_mask = "".join("1" if d.known else "0" for d in reversed(chain))
    emit(f"SDR {len(chain)} TDI ({_hex('0' * len(chain))}) "
         f"TDO ({_hex(bypass_tdo)}) MASK ({_hex(bypass_mask)});")

    emit("")
    emit("! --- step 2: IDCODE where available, BYPASS elsewhere ---")
    emit(f"SIR {total_ir} TDI ({_hex(_ir_stream(chain, 'IDCODE'))}) "
         f"TDO ({_hex(cap_bits)}) MASK ({_hex(cap_mask)});")
    idc_bits, idc_mask = "", ""
    for d in reversed(chain):
        if d.idcode_value is not None:
            idc_bits += format(d.idcode_value, "032b")[::-1]
            idc_mask += format(d.idcode_mask or 0xFFFFFFFF, "032b")[::-1]
        else:
            idc_bits += "0"
            idc_mask += "1" if d.known else "0"
    emit(f"SDR {len(idc_bits)} TDI ({_hex('0' * len(idc_bits))}) "
         f"TDO ({_hex(idc_bits)}) MASK ({_hex(idc_mask)});")

    emit("")
    if chain and all(d.boundary_length for d in chain):
        total_b = sum(d.boundary_length for d in chain)
        emit("! --- step 3: SAMPLE/PRELOAD (outputs stay inactive) ---")
        emit(f"SIR {total_ir} TDI ({_hex(_ir_stream(chain, 'SAMPLE'))}) "
             f"TDO ({_hex(cap_bits)}) MASK ({_hex(cap_mask)});")
        emit(f"SDR {total_b} TDI ({_hex('0' * total_b)}) "
             f"TDO ({_hex('0' * total_b)}) MASK ({_hex('0' * total_b)});")
    else:
        emit("! --- step 3 skipped: BOUNDARY_LENGTH unknown for some devices ---")

    emit("")
    emit("STATE RESET;")
    return "\n".join(out) + "\n"
